name: Setup Repo
description: Prepare repo

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
    - name: setup Node
      uses: actions/setup-node@v6
      with:
        node-version: 20.x
        node-version-file: '.node-version'
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'
    - run: pnpm i --frozen-lockfile
      shell: bash
